#!/usr/bin/env bash
# Install and configure our new load balancer
sudo apt-get update
sudo apt-get -y install haproxy=1.5\*
sudo sed -i '8i ENABLED=1' /etc/default/haproxy
sudo sed -i "$ a listen appname :80\n\tmode http\n\tbalance roundrobin\n\tserver 403-web-01 35.231.59.21 check\n\tserver 403-web-02 34.73.27.209 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart