#!/usr/bin/env bash
#Printing certain lines on certain iterations of a loop
i=1
while [ $i -lt 21 ];
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	let i++
done
