#!/usr/bin/env bash
#Checking attributes of a given file
if [ -a "holbertonschool" ]
then

    echo "holbertonschool file exists";
    if [ -f "holbertonschool" ]
    then
	echo "holbertonschool is a regular file"
    fi
    if [ -s "holbertonschool" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
