#!/usr/bin/env bash
# In this file we will install and start nginx and set the return page on a curl request be only text
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index/html
sudo service nginx restart
