#!/usr/bin/env bash
# Redirect a web request
apt-get update
sudo apt-get -y install nginx
source="/etc/nginx/sites-available/default"
sed -i "s|^server {|server {\n\tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n|g" $source
service nginx restart
