#!/usr/bin/env bash
# Redirect a web request
source="/etc/nginx/sites-available/default"
sed -i "s|^server {|server {\n\tlocation /redirect_me {\n\treturn 301 pmlave.website;\n\t}\n|g" $source
service nginx restart
